/**
 * flood.ts -- fill BLOCKS on Midnight with cheap unshielded NIGHT transfers.
 *
 * WHAT CHANGED AND WHY (read this before running anything)
 * -------------------------------------------------------
 * The previous version never successfully submitted a single transaction. Three
 * of its founding assumptions were wrong, all verified against the installed SDK:
 *
 *  1. EVERY OUTPUT NEEDS A TOKEN TYPE. wallet-sdk-facade's
 *       interface TokenTransfer { type: RawTokenType; receiverAddress; amount }
 *     makes `type` mandatory. The old code set it only on the WRAPPER
 *     ({type:'unshielded', outputs}) and never on the outputs, then hid the
 *     resulting compile error behind `as any`. The balancer filters candidate
 *     coins with `coin.type === tokenType`, matched nothing against `undefined`,
 *     and threw -- surfacing as the bare string "Insufficient funds" in
 *     split.jsonl. No choice of --split-into/--coin-star could ever have fixed it.
 *
 *  2. UNSHIELDED TRANSFERS ARE NOT PROOF-FREE. finalizeRecipe -> facade
 *     finalizeTransaction -> `this.provingService.prove(tx)`. The DUST fee spend
 *     is a DustSpend<PreProof> and must be proven. It is a small fixed circuit,
 *     nothing like k=18, but the proof server IS in the hot path of every tx.
 *
 *  3. ONE DUST COIN = ONE IN-FLIGHT FEE-PAYING TX. dust-wallet's
 *     availableDustTokens() filters out every coin whose nonce is in pendingDust,
 *     and the successor coin cannot be built locally -- it needs a chain-assigned
 *     commitment index delivered by the dustSpendProcessed event on sync. So a
 *     wallet holding ONE dust coin is pinned to one fee-paying transaction per
 *     inclusion+sync round trip (~1 per 6s block), no matter how fast proving or
 *     node ingest are. THIS, not proving, is the throughput ceiling.
 *
 * NOTE (measured after the fact): the engine/ammo separation described below
 * turned out to be UNNECESSARY. Dust registration is bound to the night KEY, not
 * to a single UTXO, so every output of a split inherits registration and keeps
 * generating dust. Splitting into N coins simply yields N dust coins -- i.e. N
 * concurrent lanes -- with nothing to protect. The text is kept because the
 * SIZING logic still holds; only the protection rationale is obsolete.
 *
 * THE ENGINE / AMMO MODEL (superseded -- see note above)
 * -----------------------
 * DUST is generated by REGISTERED NIGHT UTXOs, and spending a registered UTXO
 * stops its generator (a dtime is set and the dust decays over
 * dustGracePeriodSeconds = 3h). So the two roles must never be mixed:
 *
 *   ENGINE coins -- registered, LARGE, never spent. Each one is an independent
 *                   dust coin, so ENGINE COUNT = MAX CONCURRENT IN-FLIGHT TXS
 *                   for that wallet. This is the throughput dial.
 *   AMMO coins   -- unregistered, SMALL, spent freely by the churn loop.
 *
 * They are told apart by meta.registeredForDustGeneration -- the chain's own
 * flag, not local bookkeeping, so it survives restarts.
 *
 * WHY ENGINES ARE LARGE AND AMMO IS SMALL: the balancer's chooseCoin sorts
 * candidates ASCENDING and takes the smallest that matches. Making every engine
 * bigger than every ammo coin means the balancer consumes ammo first and only
 * reaches an engine if ammo is exhausted -- the separation is enforced by coin
 * size, not by hope. The churn loop additionally refuses to build a transfer it
 * cannot cover from ammo alone, so an engine is never silently eaten.
 *
 * PHASES
 *   --phase deregister OPTIONAL. Releases a NIGHT UTXO from dust generation.
 *                     NOT required before spending -- that was a wrong guess;
 *                     error 192 turned out to be a missing signature, not a
 *                     registration conflict. Kept because deliberately retiring
 *                     an engine is still a thing you may want to do.
 *   --phase split     one self-transfer per wallet: the funded UTXO -> E large
 *                     engine outputs + A small ammo outputs.
 *   --phase register  register the E largest unregistered native UTXOs for DUST
 *                     generation. Run AFTER split confirms. Idempotent.
 *   --phase churn     THE LOAD GENERATOR. Repeated N-output SELF-transfers using
 *                     ammo only. Self-transfer means ammo is never depleted and
 *                     no wallet starves, unlike the old round-robin drain.
 *                     --lanes N runs N concurrent workers per wallet, which is
 *                     how you actually steer block fullness. NOTE: --outputs is
 *                     NOT a useful dial -- measured on chain, a 32-output
 *                     transfer is 3,851 B against a 3,816 B two-output baseline,
 *                     i.e. ~1.2 B per extra output. Transfer size is dominated by
 *                     the fixed DUST spend proof, so bytes/sec is governed by
 *                     TRANSACTIONS IN FLIGHT, not by transaction size.
 *   --phase flood     legacy 1-output round-robin/sink transfers, bug-fixed.
 *                     Kept for comparison; churn is strictly better for fullness.
 *
 * MEASURED SIZING INPUTS (preview, from midnight_dust_probe.py):
 *   block cadence 6.000s | block_usage limit 200,000 B (protocol constant)
 *   1-output transfer ~673 B | transfer with change ~3,816 B | k=18/19 call ~8,151 B
 *   => 50% fullness = 100,000 B/block = ~26 change-carrying transfers/block
 *      = ~4.4 tx/s sustained.
 */
import { readFileSync, appendFileSync, existsSync } from 'node:fs';
import { ttlOneHour } from '@midnight-ntwrk/midnight-js-utils';
import * as ledger from '@midnight-ntwrk/ledger-v8';
import { buildWallet, waitForRealSync, NETWORK_ID, PROOF_SERVER_URL,
  PROOF_SERVERS, pickProofServer, saveSnapshot } from './providers.js';

interface WalletSpec { label: string; seed: string; }

/** The native NIGHT token type. Read from the ledger, never hardcoded. */
const NIGHT: string = ledger.nativeToken().raw;
const STARS_PER_NIGHT = 1_000_000n;

/** Native NIGHT test, shared with wallet_status/fleet_audit semantics. */
const isNight = (t: unknown) => { const s = String(t ?? ''); return s === '' || s === NIGHT || /^0+$/.test(s); };

function parseArgs(argv: string[]): Record<string, string | boolean> {
  const out: Record<string, string | boolean> = {};
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (!a.startsWith('--')) continue;
    const key = a.slice(2);
    const next = argv[i + 1];
    if (next && !next.startsWith('--')) { out[key] = next; i++; } else out[key] = true;
  }
  return out;
}
const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));
const nightStr = (star: bigint) => `${star / STARS_PER_NIGHT}`;

class RateGovernor {
  private tokens: number;
  private last = Date.now();
  constructor(private ratePerSec: number, private burst: number) { this.tokens = burst; }
  async take(): Promise<void> {
    if (this.ratePerSec <= 0) return;
    for (;;) {
      const now = Date.now();
      this.tokens = Math.min(this.burst, this.tokens + ((now - this.last) / 1000) * this.ratePerSec);
      this.last = now;
      if (this.tokens >= 1) { this.tokens -= 1; return; }
      await sleep(Math.max(5, (1 - this.tokens) / this.ratePerSec * 1000));
    }
  }
}

/**
 * One state snapshot.
 *
 * The old implementation called sub.unsubscribe() from INSIDE the subscribe
 * callback. If the observable emits synchronously on subscribe, `sub` is still
 * in its temporal dead zone there, the ReferenceError is swallowed by an empty
 * catch, and the subscription LEAKS -- thousands of live subscriptions over a
 * long run. Assigning the handle first and unsubscribing on the next microtask
 * makes the teardown reachable in both the sync and async emission cases.
 */
function snapshot(wallet: any, timeoutMs = 15_000): Promise<any> {
  return new Promise((resolve) => {
    let sub: any;
    let done = false;
    const finish = (s: any) => {
      if (done) return;
      done = true;
      clearTimeout(timer);
      resolve(s);
      queueMicrotask(() => { try { sub?.unsubscribe?.(); } catch { /* ignore */ } });
    };
    // A dead wallet's state() may never emit. Without a timeout the lane awaits
    // forever and the run looks idle rather than broken -- which is exactly how
    // the 403-killed wallets presented. Resolving null lets the caller treat
    // "no state" as "dead" and rebuild.
    const timer = setTimeout(() => finish(null), timeoutMs);
    try {
      sub = wallet.state().subscribe(finish);
    } catch {
      finish(null);
    }
  });
}

/**
 * Is this wallet's sync dead?
 *
 * The failure this guards against: wallet-sdk-indexer-client builds its GraphQL
 * WebSocket with `shouldRetry: () => false`, so ONE refused connect is permanent.
 * The wallet then sits at isConnected=false forever and raises nothing. Observed
 * for real -- a transient `Forbidden` from the indexer took two wallets to zero
 * throughput for the remaining six minutes of a run, silently. From the outside
 * a throttled wallet and an idle chain look identical, which makes any long run
 * untrustworthy without this check.
 */
function syncLooksBroken(st: any): boolean {
  if (!st) return true;                       // no state at all (timed out)
  const u = st?.unshielded?.progress;
  const d = st?.dust?.progress;
  if (!u || !d) return true;
  return !(Boolean(u.isConnected) && Boolean(d.isConnected));
}

const addrOf = (st: any): any => st?.unshielded?.address ?? null;
/** UnshieldedAddress exposes `hexString`; it has NO toString(networkId) -- the
 *  old addressId() therefore returned "[object Object]" for every wallet and
 *  made the startup logs identical and useless. */
const addrId = (a: any): string => { try { return String(a?.hexString ?? ''); } catch { return ''; } };

const unshieldedCoins = (st: any): any[] => (st?.unshielded?.availableCoins ?? []) as any[];
const nativeCoins = (st: any) => unshieldedCoins(st).filter((c) => isNight(c?.utxo?.type));
const engineCoins = (st: any) => nativeCoins(st).filter((c) => c?.meta?.registeredForDustGeneration);
/**
 * Coins the load generator may spend.
 *
 * MEASURED, and it overturns the engine/ammo design above: after splitting one
 * registered 5000-NIGHT UTXO into 32 outputs, ALL 32 came back
 * registeredForDustGeneration=true, and the wallet reported 33 available dust
 * coins. Dust registration is therefore bound to the NIGHT KEY, not to an
 * individual UTXO -- outputs inherit it, and spending a registered coin does
 * NOT stop dust generation.
 *
 * So there is nothing to protect and nothing to keep separate: every native coin
 * is simultaneously spendable ammunition AND a dust generator. Filtering to
 * unregistered coins (the old ammoCoins) returned an EMPTY set on a registered
 * wallet and would have stalled the churn loop forever.
 *
 * The useful consequence is much better than the original plan: splitting into N
 * coins yields N dust coins, and dust coins are what cap concurrent in-flight
 * transactions. 32 outputs bought w001 33 lanes.
 */
const spendableCoins = (st: any) => nativeCoins(st);
const coinVal = (c: any) => BigInt(c?.utxo?.value ?? 0);
const sumVal = (cs: any[]) => cs.reduce((a, c) => a + coinVal(c), 0n);
const dustAvail = (st: any) => (st?.dust?.availableCoins ?? []).length;
const dustPending = (st: any) => (st?.dust?.pendingCoins ?? []).length;

/** Build the outputs array for a transfer. `type` is MANDATORY (see header). */
const mkOutputs = (addr: any, n: number, amount: bigint) =>
  Array.from({ length: n }, () => ({ type: NIGHT, receiverAddress: addr, amount }));

/**
 * Build a transfer recipe WITHOUT proving or submitting.
 *
 * This is the cheap, on-chain-free way to validate the token-type fix: the old
 * code failed inside transferTransaction with "Insufficient funds" (the balancer
 * could not match `coin.type === undefined`), so a recipe that builds at all
 * proves the fix. Nothing reaches the chain. It DOES move the selected UTXOs to
 * locally-pending, which a process restart clears, so treat it as a one-shot
 * check rather than something to loop on.
 */

/**
 * Bound an SDK call that has no timeout of its own.
 *
 * The SDK's prove and submit calls can park forever: a 240s churn was observed
 * still alive after 31 minutes with one lane stuck inside an await. The hard
 * stop guarantees the PROCESS ends, but not that the RUN keeps its strength --
 * the watchdog cannot rescue a lane blocked inside an await (it rebuilds the
 * wallet while the lane still holds the old call), so a hung lane is lost for
 * the remainder of the run and throughput silently erodes.
 *
 * Timeouts are deliberately NOT retried. A submit that timed out may still have
 * reached the chain, and while a rebuild cannot double-spend (the coins are
 * already spent on-chain, so the node simply rejects it) it would burn a proof
 * to learn that. Freeing the lane is the win; the next iteration proceeds
 * normally, and landings are confirmed from the indexer regardless.
 */
class StageTimeout extends Error {}

async function withTimeout<T>(p: Promise<T>, ms: number, what: string): Promise<T> {
  let timer: ReturnType<typeof setTimeout> | undefined;
  try {
    return await Promise.race([
      p,
      new Promise<never>((_, reject) => {
        timer = setTimeout(() => reject(new StageTimeout(`stage '${what}' exceeded ${ms}ms`)), ms);
      }),
    ]);
  } finally {
    if (timer) clearTimeout(timer);
  }
}

async function dryRunTransfer(
  bundle: any, outputs: { type: string; receiverAddress: any; amount: bigint }[],
): Promise<{ buildMs: number }> {
  const t0 = Date.now();
  await bundle.wallet.transferTransaction(
    [{ type: 'unshielded', outputs }],
    { shieldedSecretKeys: bundle.zswapSecretKeys, dustSecretKey: bundle.dustSecretKey },
    { ttl: ttlOneHour(), payFees: true },
  );
  return { buildMs: Date.now() - t0 };
}


/**
 * Submit with a configurable wait, bypassing the facade when asked.
 *
 * WHY: facade.submitTransaction hardcodes `submissionService.submitTransaction(tx,
 * 'Finalized')`. Measured, that wait is ~19s of a ~23s cycle -- we sit through
 * several blocks of finality for a load generator that does not care. And because
 * a wallet sustains exactly ONE in-flight transaction (verified: w001 has 33 dust
 * coins and still managed one at a time; two WALLETS ran genuinely in parallel at
 * 93% concurrency), that wait IS the per-wallet cycle time. Shortening it is the
 * only lever that makes 50% fullness reachable with 15 wallets instead of ~100.
 *
 * The underlying service accepts 'Submitted' | 'InBlock' | 'Finalized'; only the
 * facade's public method is fixed. So we replicate its body -- register the
 * pending transaction, submit, return the identifier, revert on failure -- with
 * the wait we want. Both fields are ordinary properties on the facade, but if a
 * future version makes them private this falls back to the public method rather
 * than breaking.
 *
 * TRADE-OFF: with 'Submitted' the node has ACCEPTED the transaction but we have
 * not seen it in a block. Our submit count is therefore no longer proof of
 * inclusion -- landing must be confirmed from the indexer afterwards. That is
 * already how the measurement works (the generator never computes a fee), so it
 * costs nothing analytically, but never quote submit counts as landed counts.
 */
type SubmitWait = 'Submitted' | 'InBlock' | 'Finalized';

async function submitWithWait(wallet: any, finalized: any, wait: SubmitWait): Promise<string> {
  if (wait === 'Finalized') return await wallet.submitTransaction(finalized);
  const svc = wallet?.submissionService;
  const pending = wallet?.pendingTransactionsService;
  if (typeof svc?.submitTransaction !== 'function') {
    // Fast path unavailable -- do not silently change semantics, just be slow.
    return await wallet.submitTransaction(finalized);
  }
  try {
    await pending?.addPendingTransaction?.(finalized);
    await svc.submitTransaction(finalized, wait);
    return finalized.identifiers().at(-1);
  } catch (e) {
    // Mirror the facade: release the claimed UTXOs/dust so the lane is not stuck.
    try { await wallet.revert?.(finalized); } catch { /* best effort */ }
    throw e;
  }
}


/**
 * Stop wallets, but never let shutdown hang the process.
 *
 * OBSERVED: two runs were still alive 17 and 19 HOURS after finishing, holding
 * 16 established indexer connections between them. Cause: the final
 * `await Promise.allSettled(started.map(w => w.stop?.()))` never settles, so
 * main() never resolves and the `process.exit(0)` after it never runs. deploy.ts
 * documents the same hang.
 *
 * This is not just untidy. Those zombies keep syncing wallets against the
 * indexer indefinitely, which very plausibly contributed to the rate limiting we
 * had attributed purely to submission rate. Bound the wait, then leave; the
 * caller force-exits.
 */
async function shutdown(wallets: any[]): Promise<void> {
  const stops = wallets.map((w) => {
    try { return Promise.resolve(w?.stop?.()); } catch { return Promise.resolve(); }
  });
  await Promise.race([Promise.allSettled(stops), sleep(15_000)]);
}

interface StageBudgets { buildMs: number; proveMs: number; submitMs: number }

async function submitTransfer(
  bundle: any, outputs: { type: string; receiverAddress: any; amount: bigint }[],
  wait: SubmitWait = 'Finalized',
  budgets: StageBudgets = { buildMs: 120_000, proveMs: 300_000, submitMs: 180_000 },
): Promise<{ txId: string; buildMs: number; proveMs: number; submitMs: number }> {
  // Stage the timers so a slow run can be attributed. finalizeRecipe is the
  // proof-server round trip (facade -> provingService.prove); separating it from
  // build and submit is the only way to tell whether the ceiling is the prover,
  // the node, or dust availability.
  const t0 = Date.now();
  const recipe = await withTimeout(bundle.wallet.transferTransaction(
    [{ type: 'unshielded', outputs }],
    { shieldedSecretKeys: bundle.zswapSecretKeys, dustSecretKey: bundle.dustSecretKey },
    { ttl: ttlOneHour(), payFees: true },
  ), budgets.buildMs, 'build');
  // SIGN BEFORE FINALIZING. finalizeRecipe only PROVES and BINDS -- it never
  // signs. Every unshielded input needs a signature, and skipping this step got
  // the transaction rejected by the node with
  //   1010: Invalid Transaction: Custom error: 192
  // which is MalformedError::InputsSignaturesLengthMismatch (inputs != sigs).
  // Contract deploys and calls never hit this because they carry no unshielded
  // inputs, which is why the rest of the harness worked without it.
  const signed = await bundle.wallet.signRecipe(
    recipe, (data: Uint8Array) => bundle.unshieldedKeystore.signData(data),
  );
  const t1 = Date.now();
  const finalized = await withTimeout(
    bundle.wallet.finalizeRecipe(signed), budgets.proveMs, 'prove');
  const t2 = Date.now();
  const txId = await withTimeout(
    submitWithWait(bundle.wallet, finalized, wait), budgets.submitMs, 'submit');
  return { txId, buildMs: t1 - t0, proveMs: t2 - t1, submitMs: Date.now() - t2 };
}


/**
 * Unwrap an SDK error into something actionable.
 *
 * "Transaction submission error" and "Failed to prove transaction" are catch-all
 * wrappers; the real reason (node rejection text, HTTP status, WASM panic,
 * Effect _tag) is buried in a .cause/.error chain. deploy.ts learned this the
 * hard way -- same walk here so a failed submit says WHY on the first attempt
 * instead of costing another 10-minute cold sync to diagnose.
 */
function describeError(e: any): string {
  const parts: string[] = [];
  const seen = new Set<any>();

  // Effect wraps every failure from runPromise in a FiberFailure, and stashes the
  // real Cause under a well-known SYMBOL -- not under .cause. Walking only
  // .cause/.error therefore stops at the useless top-level wrapper, which is why
  // the first attempt reported nothing but "Transaction submission error".
  const effectCause = (o: any): any => {
    for (const sym of Object.getOwnPropertySymbols(o ?? {})) {
      if (String(sym).includes('Cause')) return (o as any)[sym];
    }
    return undefined;
  };

  const walk = (cur: any, depth: number, path: string) => {
    if (!cur || depth > 8 || seen.has(cur)) return;
    seen.add(cur);
    const bits: string[] = [];
    if (typeof cur === 'string') { parts.push(`${path} "${cur.slice(0, 300)}"`); return; }
    if (cur.message) bits.push(String(cur.message).slice(0, 300));
    if (cur._tag) bits.push(`_tag=${cur._tag}`);
    if (cur.name && cur.name !== 'Error') bits.push(`name=${cur.name}`);
    if (cur.status) bits.push(`status=${cur.status}`);
    if (cur.code) bits.push(`code=${cur.code}`);
    if (cur.response?.status) bits.push(`http=${cur.response.status}`);
    if (cur.body) bits.push(`body=${String(cur.body).slice(0, 300)}`);
    // Effect Cause nodes carry the payload on .error / .defect rather than .cause.
    if (typeof cur.error === 'string') bits.push(`error=${cur.error.slice(0, 300)}`);
    if (typeof cur.defect === 'string') bits.push(`defect=${cur.defect.slice(0, 300)}`);
    if (bits.length) parts.push(`${path} ${bits.join('  ')}`);
    // Anything left that is not a known key and looks informative.
    for (const k of Object.getOwnPropertyNames(cur)) {
      if (['message', 'stack', 'name', '_tag', 'cause', 'error', 'defect'].includes(k)) continue;
      const v = (cur as any)[k];
      if (typeof v === 'string' && v.length && v.length < 300) parts.push(`${path}.${k}="${v}"`);
    }
    for (const [k, v] of [['cause', cur.cause], ['error', cur.error], ['defect', cur.defect],
                          ['left', cur.left], ['right', cur.right], ['effect', effectCause(cur)]] as const) {
      if (v && typeof v === 'object') walk(v, depth + 1, `${path}.${k}`);
      else if (typeof v === 'string' && k !== 'cause') { /* already captured above */ }
    }
  };
  walk(e, 0, '[e]');
  return parts.join(' | ') || String(e);
}


/**
 * Which ledger rejections are worth retrying, and why.
 *
 * Codes come from the node's own mapping in
 * midnight-node/ledger/src/versions/common/types.rs (`From<LedgerApiError> for u8`),
 * surfaced to us as `1010: Invalid Transaction: Custom error: N`.
 *
 *   170 InvalidDustSpendProof   -- the dust spend proof was built against a dust
 *                                  merkle-tree view that the chain has already
 *                                  moved past. Purely a staleness race: observed
 *                                  on w009's split, and an immediate retry
 *                                  succeeded. This is the intermittent 5-15%
 *                                  failure that dogged every run in this harness.
 *   171 OutOfDustValidityWindow -- same family: our dust view sat outside the
 *                                  window the ledger will accept.
 *   228 IntentTtlExpired        -- the transaction took longer to build+prove
 *                                  than its TTL allowed. A rebuild gets a fresh TTL.
 *
 * Everything else is deliberately NOT retried. 192 (InputsSignaturesLengthMismatch)
 * and 138 (BalanceCheckOverspend) are deterministic construction bugs -- retrying
 * them just burns proofs and hides the defect, which is exactly how they stayed
 * unexplained for so long.
 *
 * A retry must REBUILD from scratch, not resubmit: the stale proof is baked into
 * the finalized transaction. The failed attempt reverts its coin claims (the
 * facade reverts on throw, and submitWithWait reverts explicitly), so a fresh
 * build gets clean inputs.
 */
const RETRYABLE_LEDGER_CODES = new Map<number, string>([
  [170, 'InvalidDustSpendProof'],
  [171, 'OutOfDustValidityWindow'],
  [228, 'IntentTtlExpired'],
]);

function retryableCode(detail: string): number | null {
  const m = /Custom error:\s*(\d+)/.exec(detail);
  if (!m) return null;
  const code = Number(m[1]);
  return RETRYABLE_LEDGER_CODES.has(code) ? code : null;
}

let retriedTotal = 0;

/** submitTransfer with bounded rebuild-and-retry on transient ledger rejections. */
async function submitTransferRetrying(
  bundle: any,
  outputs: { type: string; receiverAddress: any; amount: bigint }[],
  wait: SubmitWait,
  opts: { attempts: number; delayMs: number; label: string; budgets: StageBudgets },
): Promise<{ txId: string; buildMs: number; proveMs: number; submitMs: number; retries: number }> {
  let lastErr: any;
  for (let attempt = 1; attempt <= opts.attempts; attempt++) {
    try {
      const r = await submitTransfer(bundle, outputs, wait, opts.budgets);
      return { ...r, retries: attempt - 1 };
    } catch (e: any) {
      lastErr = e;
      if (e instanceof StageTimeout) throw e;   // see withTimeout: never retried
      const detail = describeError(e);
      const code = retryableCode(detail);
      if (code === null || attempt === opts.attempts) throw e;
      retriedTotal++;
      console.error(`  [${opts.label}] ${code} ${RETRYABLE_LEDGER_CODES.get(code)} ` +
        `-- rebuilding (attempt ${attempt + 1}/${opts.attempts})`);
      // Linear backoff: the dust tree needs a moment to advance and our sync to
      // catch up. Sub-second retries just reproduce the same stale view.
      await sleep(opts.delayMs * attempt);
    }
  }
  throw lastErr;
}

const isDustBlocked = (msg: string) =>
  /dust/i.test(msg) && /(balance|insufficient|could not)/i.test(msg);


/**
 * Fail fast if the proof server is not up.
 *
 * Every transaction here needs it -- even an unshielded transfer, because the
 * DUST fee spend is a proven DustSpend. When the container was down, a run
 * produced 61 consecutive failures reading
 *   'check' returned an error: FetchError: request to http://127.0.0.1:6300/check failed
 * with nothing pointing at the cause, after paying a full multi-minute wallet
 * warm-up first. Ten seconds here saves that.
 */
async function assertProofServer(url: string): Promise<void> {
  const base = url.replace(/\/$/, '');
  try {
    const res = await fetch(`${base}/health`, {
      signal: AbortSignal.timeout(10_000),
    } as any);
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    console.log(`  proof server ok at ${base}`);
  } catch (e: any) {
    throw new Error(
      `proof server unreachable at ${base}/health (${e?.message ?? e}). ` +
      `Every transaction needs it, including unshielded transfers (the DUST fee ` +
      `spend is proven). Start it with: docker start <proof-server-container>, ` +
      `then re-run. Refusing to burn a wallet warm-up on a run that cannot succeed.`,
    );
  }
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  const phase = String(args.phase ?? '');
  if (!['deregister', 'split', 'register', 'churn', 'flood'].includes(phase)) {
    throw new Error('pass --phase deregister | split | register | churn | flood');
  }

  const walletsFile = String(args.wallets ?? 'fleet.json');
  let wallets: WalletSpec[] = JSON.parse(readFileSync(walletsFile, 'utf8'));
  if (args.only) {
    const want = new Set(String(args.only).split(',').map((s) => s.trim()));
    wallets = wallets.filter((w) => want.has(w.label));
  }
  const maxWallets = Number(args['max-wallets'] ?? 0);
  if (maxWallets > 0 && maxWallets < wallets.length) wallets = wallets.slice(0, maxWallets);
  if (!wallets.length) throw new Error(`no wallets selected from ${walletsFile}`);

  // Startup stagger is a RATE-LIMIT control, not just a memory one. The preview
  // indexer 403s an IP at roughly >=5 req/s and hard-blocks near 12 req/s; every
  // wallet cold-sync is a burst of indexer traffic. 3s default keeps 15 wallets
  // well inside the safe envelope.
  const staggerMs = Number(args['stagger-ms'] ?? 3000);
  const targetTps = Number(args['target-tps'] ?? 0);
  // Burst allowance. Defaults to ONE SECOND of the target rate, not 20.
  //
  // The old default of 20 meant the first 20 transactions bypassed --target-tps
  // completely: measured at --target-tps 0.30 the run emitted 17 transactions in
  // its first 30s (0.57 tx/s), because 20 tokens were available immediately and
  // the governor never engaged. For an experiment about how the chain responds
  // to sustained utilisation, opening with an uncontrolled spike is precisely
  // the wrong shape -- and it would have been invisible in the run average.
  const burst = Number(args.burst ?? Math.max(1, Math.ceil(targetTps)));
  const haltFile = args['halt-file'] ? String(args['halt-file']) : '';
  const log = String(args.log ?? `${phase}.jsonl`);
  const durationS = Number(args['duration-s'] ?? 300);
  // DEFAULT 1, deliberately. Outputs cost ~1.2 bytes each (measured: a 32-output
  // split is 3,851 B against a 3,816 B two-output baseline), so extra outputs buy
  // no block fullness at all. What they DO buy is UTXO growth: at N outputs a
  // wallet nets +(N-1) coins per transaction, and a 2-hour run at ~4.4 tx/s is
  // ~31,000 transactions -- thousands of surplus UTXOs per wallet, degrading sync
  // and memory for zero benefit. One output in, one out, coin count flat.
  const outputsPerTx = Number(args.outputs ?? 1);
  // --dry-run: build the recipe and stop. Validates the token-type fix with no
  // on-chain effect and, critically, without destroying a wallet's dust engine.
  // --submit-wait Submitted|InBlock|Finalized. Default keeps the facade's
  // behaviour; 'Submitted' is the throughput setting (see submitWithWait).
  const submitWait = (['Submitted', 'InBlock', 'Finalized'] as const)
    .find((w) => w === String(args['submit-wait'] ?? '')) ?? 'Finalized';
  // Transient-rejection retry (see RETRYABLE_LEDGER_CODES). 3 attempts total.
  const attempts = Math.max(1, Number(args.retries ?? 3));
  const retryDelayMs = Number(args['retry-delay-ms'] ?? 1500);
  // Per-stage ceilings. Generous relative to observed medians (build ~0.2s,
  // prove ~2.3s, submit ~1.2s on the fast path / ~19s waiting for Finalized) so
  // they only ever catch a genuine hang, never normal slowness.
  const budgets: StageBudgets = {
    buildMs: Number(args['build-timeout-ms'] ?? 120_000),
    proveMs: Number(args['prove-timeout-ms'] ?? 300_000),
    submitMs: Number(args['submit-timeout-ms'] ?? 180_000),
  };
  const dryRun = 'dry-run' in args;
  // --sweep 128,96,64,...  descending output counts to calibrate max tx size.
  const sweep = args.sweep && args.sweep !== true
    ? String(args.sweep).split(',').map((x) => Number(x.trim())).filter((n) => n > 0)
    : [];

  // split knobs, expressed in NIGHT for legibility.
  const engines = Number(args.engines ?? 4);
  const engineNight = BigInt(String(args['engine-night'] ?? '500'));
  const ammo = Number(args.ammo ?? 150);
  // --coins N: split the whole native balance into N EQUAL-VALUE coins.
  //
  // This is the correct shape and supersedes the engines/ammo split. The
  // balancer selects smallest-first and accumulates until the target is covered,
  // so a wallet holding MIXED values fragments: once the small coins run out the
  // balancer takes a large one and emits change at a brand-new value, and coin
  // count drifts downward from there. Observed for real -- w001 went from 32
  // coins to 10 across a few runs, silently reducing its throughput.
  //
  // With every coin equal to V, a transfer targeting V consumes exactly one coin
  // and emits exactly one coin of V. Stable indefinitely, at any lane count.
  const uniformCoins = Number(args.coins ?? 0);
  const ammoNight = BigInt(String(args['ammo-night'] ?? '20'));

  console.log(`network=${NETWORK_ID}  phase=${phase}  wallets=${wallets.length}` +
    `  ${targetTps ? `target-tps=${targetTps}` : 'target-tps=FLAT-OUT'}`);
  if (phase === 'split') {
    console.log(`  plan per wallet: ${engines} engine x ${engineNight} NIGHT (registered, never spent)` +
      ` + ${ammo} ammo x ${ammoNight} NIGHT`);
    console.log(`  total needed: ${engines * Number(engineNight) + ammo * Number(ammoNight)} NIGHT`);
  }
  if (phase === 'churn') console.log(`  outputs/tx=${outputsPerTx}  duration=${durationS}s` +
    `  (note: outputs cost only ~1.2 B each -- tx size is ~3,850 B regardless,` +
    ` so use --lanes, not --outputs, to drive fullness)`);
  console.log(`  retries=${attempts} (transient ledger codes only: ` +
    `${[...RETRYABLE_LEDGER_CODES.keys()].join('/')})`);
  console.log(`  submit-wait=${submitWait}` +
    (submitWait === 'Finalized' ? '  (waits for finality: ~19s of a ~23s cycle)'
                                : '  (fast path -- confirm landings via the indexer, not our submit count)'));
  if (dryRun) console.log('  DRY RUN -- recipes are built but never proven or submitted.');

  for (const u of (PROOF_SERVERS.length ? PROOF_SERVERS : [PROOF_SERVER_URL])) {
    await assertProofServer(u);
  }

  const governor = new RateGovernor(targetTps, burst);
  const started: any[] = [];
  let submitted = 0, failed = 0, dustBlocked = 0, timedOut = 0;

  const bundles: {
    spec: WalletSpec; bundle: any; addr: any; id: string;
    reviving?: Promise<void>; revivals: number; strikes: number; nextTryMs: number;
    lastOkAt: number; lastApplied: string; lastAppliedAt: number;
    resplitting?: boolean; resplits: number;
  }[] = [];
  await Promise.all(wallets.map(async (spec, i) => {
    if (staggerMs) await sleep(i * staggerMs);
    try {
      // Spread wallets across the proof server pool: one server saturates at
      // ~5.2 proofs/s, so capacity comes from more servers, not more load.
      const bundle = await buildWallet(spec.seed, {
        proofServerUrl: pickProofServer(i),
        snapshotLabel: spec.label,     // restore prior sync state if we have it
      });
      // A wallet that has never been registered has NO dust by definition --
      // dust is generated by registered NIGHT UTXOs. Demanding dust coins before
      // the registration phase is a deadlock: the wallet cannot get dust until it
      // registers, and cannot register until it has dust. So the register phase
      // waits only for the unshielded side to be real.
      await waitForRealSync(bundle.wallet, {
        label: spec.label, requireDustCoins: phase !== 'register',
      });
      started.push(bundle.wallet);
      // Snapshot the freshly-synced state so the next run restores in seconds
      // instead of paying the 30-45 minute cold sync again.
      await saveSnapshot(spec.label, spec.seed, bundle);
      const st = await snapshot(bundle.wallet);
      const addr = addrOf(st);
      bundles.push({ spec, bundle, addr, id: addrId(addr),
        revivals: 0, strikes: 0, nextTryMs: 0,
        lastOkAt: Date.now(), lastApplied: '', lastAppliedAt: Date.now(), resplits: 0 });
      console.log(`  [${spec.label}] ready  native=${nightStr(sumVal(nativeCoins(st)))} NIGHT` +
        `  coins=${nativeCoins(st).length} registered=${engineCoins(st).length}` +
        `  dust=${dustAvail(st)}avail/${dustPending(st)}pend`);
    } catch (e: any) {
      console.error(`  [${spec.label}] build/sync failed: ${e?.message?.slice(0, 160)}`);
    }
  }));
  if (!bundles.length) throw new Error('no wallets synced; nothing to do');

  const logRec = (o: any) => appendFileSync(log, JSON.stringify({ ...o, t: new Date().toISOString() }) + '\n');

  // ------------------------------------------------------------- DEREGISTER --
  if (phase === 'deregister') {
    for (const { spec, bundle } of bundles) {
      try {
        const st = await snapshot(bundle.wallet);
        const regd = engineCoins(st);
        if (!regd.length) {
          console.log(`  [${spec.label}] nothing registered -- already spendable.`);
          continue;
        }
        console.log(`  [${spec.label}] deregistering ${regd.length} UTXO(s): ` +
          regd.map((c) => `${nightStr(coinVal(c))}N`).join(', ') + ' ...');
        const recipe = await bundle.wallet.deregisterFromDustGeneration(
          regd,
          bundle.unshieldedKeystore.getPublicKey(),
          (payload: Uint8Array) => bundle.unshieldedKeystore.signData(payload),
        );
        // DO NOT signRecipe() HERE.
        //
        // registerNightUtxosForDustGeneration / deregisterFromDustGeneration
        // already take a signing callback and attach the dust-registration
        // signature themselves. Calling signRecipe on top makes the facade's
        // #signDustRegistrationIfPresent attach a SECOND signature, and the node
        // rejects the result with Custom error 192
        // (MalformedError::InputsSignaturesLengthMismatch) -- the same code as a
        // MISSING signature, from the opposite cause. All 7 registrations failed
        // this way. wallet_status.ts registers w001-w015 with no signRecipe and
        // has always worked; that is the reference behaviour.
        //
        // signRecipe IS required for plain transfers (split/churn/flood), where
        // nothing else signs the unshielded inputs.
        const finalized = await bundle.wallet.finalizeRecipe(recipe);
        const txId = await bundle.wallet.submitTransaction(finalized);
        submitted++;
        logRec({ phase, wallet: spec.label, txId, deregistered: regd.length });
        console.log(`  [${spec.label}] deregistration submitted: ${txId}`);
      } catch (e: any) {
        failed++;
        const detail = describeError(e);
        console.error(`  [${spec.label}] deregister FAILED: ${detail}`);
        logRec({ phase, wallet: spec.label, error: detail });
      }
    }
    console.log(`\nderegister done. ${submitted} submitted, ${failed} failed.`);
    console.log('Wait for confirmation, then --phase split. The 3h dust grace period');
    console.log('starts now, but fees are 1 SPECK so this is not a real time pressure.');
    await shutdown(started);
    return;
  }

  // ------------------------------------------------------------------ SPLIT --
  if (phase === 'split') {
    for (const { spec, bundle, addr } of bundles) {
      try {
        const st = await snapshot(bundle.wallet);
        const native = sumVal(nativeCoins(st));
        const engineStar = engineNight * STARS_PER_NIGHT;
        const ammoStar = ammoNight * STARS_PER_NIGHT;
        const needed = uniformCoins > 0 ? native
          : engineStar * BigInt(engines) + ammoStar * BigInt(ammo);
        // Only NATIVE NIGHT counts. The old code summed every token type, which
        // inflated w001's balance from 5,000 to 6,700 NIGHT and made its own
        // remediation advice ("reduce to <=53") unsatisfiable.
        if (needed > native) {
          const msg = `needs ${nightStr(needed)} NIGHT but has ${nightStr(native)} native`;
          console.error(`  [${spec.label}] SKIP: ${msg}`);
          logRec({ phase, wallet: spec.label, error: msg });   // guard rejections were
          continue;                                            // previously invisible
        }
        // Fees are paid in DUST, not NIGHT, so no NIGHT headroom is required --
        // the balancer emits change only when inputs exceed the target. Spending
        // exactly `native` is legal and leaves no change UTXO.
        let outputs;
        if (uniformCoins > 0) {
          const per = native / BigInt(uniformCoins);
          if (per <= 0n) { console.error(`  [${spec.label}] SKIP: balance too small for ${uniformCoins} coins`); continue; }
          outputs = mkOutputs(addr, uniformCoins, per);
          console.log(`  [${spec.label}] splitting -> ${uniformCoins} EQUAL coins x ` +
            `${nightStr(per)} NIGHT (leftover ${nightStr(native - per * BigInt(uniformCoins))} as change)`);
        } else {
          outputs = [
            ...mkOutputs(addr, engines, engineStar),
            ...mkOutputs(addr, ammo, ammoStar),
          ];
          console.log(`  [${spec.label}] splitting -> ${engines} x ${engineNight}N engines + ${ammo} x ${ammoNight}N ammo ...`);
          console.log(`  [${spec.label}] NOTE: mixed coin values fragment under churn -- prefer --coins N`);
        }
        if (dryRun && sweep.length) {
          // CALIBRATION. Find the largest single transfer the ledger will accept.
          // Descending, stopping at the first success, because the two outcomes
          // have different side effects: a FAILED build reverts and leaves the
          // coin spendable, while a SUCCESSFUL one leaves it locally pending --
          // so after the first success no further attempt is meaningful. Going
          // downward means every attempt before the answer is a clean revert.
          console.log(`  [${spec.label}] sweeping output counts: ${sweep.join(', ')}`);
          let best = 0;
          for (const n of sweep) {
            // Keep total value constant so only OUTPUT COUNT varies.
            const per = native / BigInt(n * 2);
            try {
              const d = await dryRunTransfer(bundle, mkOutputs(addr, n, per));
              console.log(`    ${String(n).padStart(4)} outputs -> OK (${d.buildMs}ms)  <= max accepted`);
              logRec({ phase, wallet: spec.label, sweep: n, ok: true, ...d });
              best = n;
              break;
            } catch (e: any) {
              const m = e?.message?.slice(0, 90) ?? '';
              console.log(`    ${String(n).padStart(4)} outputs -> rejected: ${m}`);
              logRec({ phase, wallet: spec.label, sweep: n, ok: false, error: m });
            }
          }
          console.log(`  [${spec.label}] LARGEST ACCEPTED TRANSFER: ${best} outputs`);
          continue;
        }
        if (dryRun) {
          const d = await dryRunTransfer(bundle, outputs);
          console.log(`  [${spec.label}] DRY RUN ok -- recipe built in ${d.buildMs}ms for ` +
            `${outputs.length} outputs. Nothing submitted, no NIGHT spent, dust engine intact.`);
          logRec({ phase, wallet: spec.label, dryRun: true, outputs: outputs.length, ...d });
          continue;
        }
        const r = await submitTransferRetrying(bundle, outputs, submitWait,
          { attempts, delayMs: retryDelayMs, label: spec.label, budgets });
        submitted++;
        logRec({ phase, wallet: spec.label, txId: r.txId, engines, ammo, ...r });
        console.log(`  [${spec.label}] split submitted: ${r.txId} ` +
          `(build ${r.buildMs}ms prove ${r.proveMs}ms submit ${r.submitMs}ms)`);
      } catch (e: any) {
        failed++;
        const detail = describeError(e);
        console.error(`  [${spec.label}] split FAILED: ${detail}`);
        if (e?.stack) console.error(`    stack: ${String(e.stack).split('\n').slice(0, 5).join(' | ')}`);
        logRec({ phase, wallet: spec.label, error: detail });
      }
    }
    console.log(`\nsplit done. ${submitted} submitted, ${failed} failed.`);
    console.log('WAIT for these to confirm, then run --phase register (the new outputs are');
    console.log('UNREGISTERED, so the wallet currently has NO dust engine and is living off');
    console.log('the 3h grace period of the coin you just spent).');
    await shutdown(started);
    return;
  }

  // --------------------------------------------------------------- REGISTER --
  if (phase === 'register') {
    for (const { spec, bundle } of bundles) {
      try {
        const st = await snapshot(bundle.wallet);
        // Engines are the LARGEST unregistered native coins -- largest so the
        // balancer (smallest-first) reaches for ammo before ever touching them.
        const cands = nativeCoins(st).filter((c) => !c?.meta?.registeredForDustGeneration).sort((a, b) => (coinVal(b) > coinVal(a) ? 1 : -1)).slice(0, engines);
        if (!cands.length) { console.log(`  [${spec.label}] nothing to register.`); continue; }
        console.log(`  [${spec.label}] registering ${cands.length} engine(s): ` +
          cands.map((c) => `${nightStr(coinVal(c))}N`).join(', '));
        const recipe = await bundle.wallet.registerNightUtxosForDustGeneration(
          cands,
          bundle.unshieldedKeystore.getPublicKey(),
          (payload: Uint8Array) => bundle.unshieldedKeystore.signData(payload),
          st?.dust?.address,
        );
        // DO NOT signRecipe() HERE.
        //
        // registerNightUtxosForDustGeneration / deregisterFromDustGeneration
        // already take a signing callback and attach the dust-registration
        // signature themselves. Calling signRecipe on top makes the facade's
        // #signDustRegistrationIfPresent attach a SECOND signature, and the node
        // rejects the result with Custom error 192
        // (MalformedError::InputsSignaturesLengthMismatch) -- the same code as a
        // MISSING signature, from the opposite cause. All 7 registrations failed
        // this way. wallet_status.ts registers w001-w015 with no signRecipe and
        // has always worked; that is the reference behaviour.
        //
        // signRecipe IS required for plain transfers (split/churn/flood), where
        // nothing else signs the unshielded inputs.
        const finalized = await bundle.wallet.finalizeRecipe(recipe);
        const txId = await bundle.wallet.submitTransaction(finalized);
        submitted++;
        logRec({ phase, wallet: spec.label, txId, engines: cands.length });
        console.log(`  [${spec.label}] registration submitted: ${txId}`);
      } catch (e: any) {
        failed++;
        const detail = describeError(e);
        console.error(`  [${spec.label}] register FAILED: ${detail}`);
        logRec({ phase, wallet: spec.label, error: detail });
      }
    }
    console.log(`\nregister done. ${submitted} submitted, ${failed} failed.`);
    console.log('Each registered engine becomes an independent DUST coin, and engine count');
    console.log('is your max concurrent in-flight txs. Dust accrues from ZERO at');
    console.log('8267 SPECK/s per STAR (7 days to cap) -- give it time before churning hard.');
    await shutdown(started);
    return;
  }

  // --------------------------------------------------------- WALLET REVIVAL --
  // Rebuild a wallet whose sync has died. Without this, a single transient 403
  // from the indexer permanently retires a lane (shouldRetry:false, see
  // isDeadState) and a long run silently decays toward zero throughput while
  // still reporting "0 failed" -- because a lane with no state never even
  // attempts a transaction.
  let revivals = 0;
  const reviveEnabled = !('no-revive' in args);

  async function reviveWallet(b: typeof bundles[number], until: number): Promise<void> {
    // Backoff is essential: the usual cause of death is being rate-limited, and
    // an immediate rebuild issues a fresh burst of cold-sync traffic at exactly
    // the moment the endpoint is refusing us. Doubling from 15s to 5 min.
    const wait = Math.max(0, b.nextTryMs - Date.now());
    if (wait > 0) {
      console.error(`  [${b.spec.label}] revival backoff ${(wait / 1000).toFixed(0)}s ...`);
      await sleep(wait);
    }
    const backoff = Math.min(300_000, 15_000 * 2 ** Math.min(b.revivals, 5));
    b.nextTryMs = Date.now() + backoff;

    // BOUND THE REVIVAL TO THE RUN. waitForRealSync defaults to
    // MN_SYNC_TIMEOUT_MS, which we set to 45 minutes for cold starts -- so a
    // revival begun near the end of a run kept the process alive 31 minutes
    // against a 10-minute deadline, and had to be killed by hand. Give the
    // rebuild only the time the run actually has left, and skip it entirely if
    // there is not enough left to be worth a cold sync.
    const remaining = until - Date.now();
    if (remaining < 90_000) {
      console.error(`  [${b.spec.label}] only ${(remaining / 1000).toFixed(0)}s left -- skipping revival`);
      return;
    }
    const syncBudget = Math.min(8 * 60_000, remaining - 20_000);

    console.error(`  [${b.spec.label}] sync is DEAD -- rebuilding wallet ` +
      `(attempt ${b.revivals + 1}, sync budget ${(syncBudget / 1000).toFixed(0)}s)`);
    try { await b.bundle?.wallet?.stop?.(); } catch { /* it is already broken */ }
    try {
      const rebuilt = await buildWallet(b.spec.seed);
      await waitForRealSync(rebuilt.wallet, {
        label: `${b.spec.label}:revive`, requireDustCoins: true, timeoutMs: syncBudget,
      });
      const st = await snapshot(rebuilt.wallet);
      b.bundle = rebuilt;
      b.addr = addrOf(st);
      b.id = addrId(b.addr);
      b.revivals++;
      b.strikes = 0;
      b.lastOkAt = Date.now();
      b.lastAppliedAt = Date.now();
      b.lastApplied = '';
      revivals++;
      started.push(rebuilt.wallet);
      console.error(`  [${b.spec.label}] REVIVED (coins=${nativeCoins(st).length} dust=${dustAvail(st)})`);
      logRec({ phase, wallet: b.spec.label, revived: true, attempt: b.revivals });
    } catch (e: any) {
      console.error(`  [${b.spec.label}] revival FAILED: ${describeError(e).slice(0, 200)}`);
      logRec({ phase, wallet: b.spec.label, reviveFailed: describeError(e).slice(0, 200) });
    }
  }

  /** Lanes call this at the top of each iteration; it serialises revival. */
  async function ensureAlive(b: typeof bundles[number]): Promise<void> {
    if (b.reviving) await b.reviving;
  }

  /**
   * One watchdog per wallet.
   *
   * VERDICT BY EVIDENCE, not by isConnected. Verified the hard way: calling
   * wallet.stop() kills the sync loops, but state() keeps replaying its last
   * value with isConnected STILL TRUE -- so an isConnected check never fires and
   * the wallet looks healthy while producing nothing. (That test is exactly why
   * this is not a one-line check.)
   *
   * The reliable signal is that a wallet has stopped MAKING PROGRESS while its
   * lanes keep trying: no successful transaction recently AND no advance in the
   * dust applied index. Lanes attempt every ~4s, so a quiet stretch this long is
   * definitive rather than a blip. A hard signal (no state, or an explicitly
   * disconnected sub-wallet) still short-circuits immediately.
   */
  const STALL_MS = Number(args['stall-ms'] ?? 120_000);

  // Coin-supply floor. Even with uniform values a long run can drift (a failed
  // balance, a contested selection, an odd change coin). Coin count IS per-wallet
  // throughput: a wallet down to one coin waits on its own change and falls to
  // ~0.05 tx/s -- a 5x loss, silently. Measured: w001 eroded 32 -> 10 coins
  // across a few runs. So a lane that sees supply run low rebuilds it.
  const minCoins = Number(args['min-coins'] ?? 6);
  const resplitInto = Number(args['resplit-into'] ?? 16);

  function startWatchdog(b: typeof bundles[number], until: number) {
    return (async () => {
      while (Date.now() < until - 30_000) {   // no point starting work we cannot finish
        await sleep(20_000);
        if (haltFile && existsSync(haltFile)) return;
        if (b.reviving) { await b.reviving; continue; }

        const st = await snapshot(b.bundle.wallet, 10_000);
        const hard = syncLooksBroken(st);

        // Track dust progress so a wallet that is merely idle-but-alive (still
        // applying chain events) is not mistaken for a dead one.
        const applied = String(st?.dust?.progress?.appliedIndex ?? '');
        if (applied && applied !== b.lastApplied) {
          b.lastApplied = applied;
          b.lastAppliedAt = Date.now();
        }

        const quietMs = Date.now() - Math.max(b.lastOkAt, b.lastAppliedAt);
        const stalled = quietMs > STALL_MS;
        if (!hard && !stalled) { b.strikes = 0; continue; }

        if (++b.strikes < 2) continue;   // one bad read is not a verdict
        const why = hard ? 'sync reports disconnected/no state'
                         : `no progress for ${(quietMs / 1000).toFixed(0)}s`;
        if (!reviveEnabled) {
          console.error(`  [${b.spec.label}] looks dead (${why}) -- revival disabled`);
          b.strikes = 0;
          continue;
        }
        console.error(`  [${b.spec.label}] ${why}`);
        b.reviving = reviveWallet(b, until).finally(() => { b.reviving = undefined; });
        await b.reviving;
      }
    })();
  }


  // ------------------------------------------------------------------ CHURN --
  // Sustained N-output SELF-transfer from ammo. Self-transfer is what makes this
  // sustainable: value returns to the same wallet, so ammo is never depleted and
  // no lane starves -- unlike round-robin, where fast lanes drain and idle.
  const deadline = Date.now() + durationS * 1000;
  const t0 = new Date().toISOString();

  // HARD STOP. The lane loops and watchdogs all honour `deadline`, and shutdown
  // is bounded -- but none of that helps if a lane is parked inside an await that
  // never resolves. There is no timeout on the SDK's prove or submit calls, so a
  // hung network call pins a lane forever: observed as a 240s churn still alive
  // after 31 minutes with no further log output.
  //
  // This is the backstop that guarantees a run ends. unref() so it never keeps an
  // otherwise-finished process alive; it only fires if something else is still
  // holding the loop open past the deadline plus grace.
  const graceS = Number(args['hard-stop-grace-s'] ?? 180);
  const hardStop = setTimeout(() => {
    console.error(`\nHARD STOP: ${graceS}s past the deadline and still running -- ` +
      `a prove/submit call is hung. Forcing exit; logs on disk are complete.`);
    process.exit(0);
  }, durationS * 1000 + graceS * 1000);
  hardStop.unref();

  if (phase === 'churn') {
    console.log(`\nchurning ${durationS}s from ${bundles.length} wallets. window starts ${t0}`);
    // CONCURRENCY LIVES HERE. Measured: submitTransaction waits for InBlock and
    // takes ~19s, while a transfer is a near-constant ~3,850 bytes no matter how
    // many outputs it carries. So bytes/second is governed purely by how many
    // transactions are in flight -- and a wallet can hold one in flight per
    // AVAILABLE DUST COIN, i.e. per registered engine. One sequential lane per
    // wallet therefore wastes ~7/8 of an 8-engine wallet's capacity.
    //
    // Concurrent builds within one wallet are safe: the SDK moves a UTXO from
    // available to pending inside the same state transaction that builds the
    // offer, so two lanes cannot claim the same coin.
    const lanes = Math.max(1, Number(args.lanes ?? 1));
    // LANE STAGGER -- measured necessity, not a nicety.
    //
    // In the first 8-lane run every transaction landed in exactly every 4th
    // block (567601, 567605, 567609, ...), 3 per block, with three empty blocks
    // between. All lanes start together and have near-identical ~24s cycles, so
    // they run in lockstep -- a convoy that delivers 100% of the load into 25%
    // of the blocks. Mean fullness looks right while the real distribution is
    // spiky, which is precisely wrong for an experiment about how the chain
    // responds to PER-BLOCK utilisation.
    //
    // Offsetting lane i by (cycle / lanes) spreads arrivals evenly across the
    // cycle. Default derives from the measured ~24s cycle; override if the
    // observed cycle moves.
    const laneStaggerMs = Number(args['lane-stagger-ms'] ?? Math.round(24000 / lanes));
    console.log(`  ${lanes} lane(s) per wallet -> ${lanes * bundles.length} concurrent in flight` +
      `  lane-stagger=${laneStaggerMs}ms`);
    if (lanes > 1) {
      console.log('  (a lane can only fly when a dust coin is free, so useful lanes');
      console.log('   are capped by each wallet\'s registered engine count.)');
    }
    const worker = async (b: typeof bundles[number], lane: number) => {
      // Spread this lane's phase within the cycle (see LANE STAGGER above).
      if (lane > 0 && laneStaggerMs > 0) await sleep(lane * laneStaggerMs);
      while (Date.now() < deadline) {
        if (haltFile && existsSync(haltFile)) return;
        await ensureAlive(b);
        const st = await snapshot(b.bundle.wallet);
        // A null/dead state means the watchdog has not noticed yet -- yield
        // rather than charging into a guaranteed failure.
        if (syncLooksBroken(st)) { await sleep(2000); continue; }
        // Dust gate FIRST: with no available dust coin the balance step is
        // guaranteed to fail, so waiting is strictly better than burning a
        // request and logging a failure. This is the ceiling described in the
        // header -- engines in flight == concurrency.
        if (dustAvail(st) === 0) { dustBlocked++; await sleep(500); continue; }
        const am = spendableCoins(st);
        const ammoTotal = sumVal(am);
        if (!am.length) { await sleep(300); continue; }

        // Coin supply low -> rebuild it from the largest coin. Guarded so only
        // one lane per wallet does this, and only if a big enough coin exists to
        // be worth splitting.
        if (am.length < minCoins && !b.resplitting) {
          const biggest = am.reduce((x, c) => (coinVal(c) > coinVal(x) ? c : x));
          const each = coinVal(biggest) / BigInt(resplitInto);
          if (each > 0n) {
            b.resplitting = true;
            try {
              console.error(`  [${b.spec.label}] coins=${am.length} < ${minCoins} -- re-splitting ` +
                `${nightStr(coinVal(biggest))}N into ${resplitInto} x ${nightStr(each)}N`);
              const rs = await submitTransferRetrying(b.bundle, mkOutputs(b.addr, resplitInto, each),
                submitWait, { attempts, delayMs: retryDelayMs, label: b.spec.label, budgets });
              b.resplits++;
              b.lastOkAt = Date.now();
              logRec({ phase, wallet: b.spec.label, resplit: resplitInto, txId: rs.txId });
            } catch (e: any) {
              logRec({ phase, wallet: b.spec.label, resplitFailed: describeError(e).slice(0, 160) });
            } finally {
              b.resplitting = false;
            }
            continue;
          }
        }
        // Size the transfer from ONE COIN, not from the wallet total.
        //
        // Sizing off the total made every concurrent lane try to move a large
        // fraction of the whole balance at once; with 8 lanes they collided and
        // 7 of 28 attempts died with "Insufficient funds". Spending roughly a
        // single coin per transaction keeps lanes disjoint: the balancer takes
        // the smallest matching coin, and a claimed coin is moved to pending
        // inside the same state transaction, so the next lane picks a different
        // one. Coin count grows slowly (1 consumed -> N emitted), which is
        // exactly what we want since coins are what create lanes.
        const smallest = am.reduce((a, c) => (coinVal(c) < coinVal(a) ? c : a));
        const per = coinVal(smallest) / BigInt(outputsPerTx);
        if (per <= 0n) { await sleep(300); continue; }
        await governor.take();          // take the token BEFORE starting the clock
        const tStart = Date.now();
        try {
          const r = await submitTransferRetrying(b.bundle, mkOutputs(b.addr, outputsPerTx, per),
            submitWait, { attempts, delayMs: retryDelayMs, label: b.spec.label, budgets });
          submitted++;
          b.lastOkAt = Date.now();   // liveness evidence for the watchdog
          logRec({ phase, wallet: b.spec.label, txId: r.txId, outputs: outputsPerTx,
            per: per.toString(), ...r, submitWait, total_ms: Date.now() - tStart });
        } catch (e: any) {
          const msg = e?.message?.slice(0, 200) ?? '';
          // Log the UNWRAPPED cause. Logging e.message alone yields a wall of
          // identical "Transaction submission error" lines with the real reason
          // (node rejection code, HTTP status) still buried in the Effect cause
          // chain -- which is exactly how error 192 and 170 stayed unexplained.
          const detail = describeError(e);
          failed++;
          if (e instanceof StageTimeout) {
            // The lane is now FREE -- that is the whole point. Log it loudly:
            // repeated timeouts mean the proof server or node is wedged, and the
            // run's throughput figures should not be read as capacity.
            timedOut++;
            console.error(`  [${b.spec.label}] ${msg} -- lane released`);
            logRec({ phase, wallet: b.spec.label, timeout: msg, total_ms: Date.now() - tStart });
            continue;
          }
          if (isDustBlocked(msg)) {
            dustBlocked++;
            // Wait for a dust coin to actually come back rather than sleeping a
            // flat interval into a guaranteed-failing retry.
            for (let i = 0; i < 40; i++) {
              await sleep(500);
              if (dustAvail(await snapshot(b.bundle.wallet)) > 0) break;
            }
          } else await sleep(200);
          logRec({ phase, wallet: b.spec.label, error: detail.slice(0, 600), total_ms: Date.now() - tStart });
        }
      }
    };
    const ticker = setInterval(() => {
      process.stdout.write(`[${new Date().toISOString().slice(11, 19)}] ` +
        `submitted=${submitted} failed=${failed} dust-blocked=${dustBlocked} revivals=${revivals}\r`);
    }, 3000);
    // TEST HOOK (--kill-after-s N): stop the first wallet's sync loops N seconds
    // in, to prove the watchdog actually detects a dead wallet and rebuilds it.
    // Off unless the flag is passed. This is the only way to exercise the revival
    // path without waiting for a real rate-limit event.
    const killAfterS = Number(args['kill-after-s'] ?? 0);
    if (killAfterS > 0 && bundles.length) {
      void (async () => {
        await sleep(killAfterS * 1000);
        const victim = bundles[0];
        console.error(`\n  [TEST] killing ${victim.spec.label} sync after ${killAfterS}s ...`);
        try { await victim.bundle.wallet.stop?.(); } catch { /* that is the point */ }
      })();
    }
    const watchdogs = reviveEnabled ? bundles.map((b) => startWatchdog(b, deadline)) : [];
    await Promise.all(bundles.flatMap((b) =>
      Array.from({ length: lanes }, (_, i) => worker(b, i))));
    await Promise.allSettled(watchdogs);
    clearInterval(ticker);
  }

  // ------------------------------------------------------------------ FLOOD --
  if (phase === 'flood') {
    const sinkLabel = args.sink ? String(args.sink) : '';
    let sink: any = null;
    if (sinkLabel) {
      const f = bundles.find((b) => b.spec.label === sinkLabel);
      if (!f) throw new Error(`--sink '${sinkLabel}' is not a synced fleet wallet label`);
      sink = f.addr;
    }
    const worker = async (b: typeof bundles[number], idx: number) => {
      let ri = idx; // per-lane cursor: a single shared counter coupled all lanes
      while (Date.now() < deadline) {
        if (haltFile && existsSync(haltFile)) return;
        await ensureAlive(b);
        const st = await snapshot(b.bundle.wallet);
        if (syncLooksBroken(st)) { await sleep(2000); continue; }
        if (dustAvail(st) === 0) { dustBlocked++; await sleep(500); continue; }
        const am = spendableCoins(st);
        if (!am.length) { await sleep(300); continue; }
        // Mirror the balancer's own choice (smallest matching coin) and send the
        // coin's FULL value. The old `val - 1n` emitted a 1-STAR change coin,
        // which then became the smallest coin and got picked first next round --
        // progressively choking the wallet with dust-of-NIGHT.
        const coin = am.reduce((a, c) => (coinVal(c) < coinVal(a) ? c : a));
        const amount = coinVal(coin);
        const dest = sink ?? (bundles[(ri++) % bundles.length].id === b.id
          ? bundles[(ri++) % bundles.length].addr : bundles[(ri) % bundles.length].addr);
        await governor.take();
        const tStart = Date.now();
        try {
          const r = await submitTransferRetrying(b.bundle,
            [{ type: NIGHT, receiverAddress: dest, amount }], submitWait,
            { attempts, delayMs: retryDelayMs, label: b.spec.label, budgets });
          submitted++;
          b.lastOkAt = Date.now();   // liveness evidence for the watchdog
          logRec({ phase, wallet: b.spec.label, txId: r.txId, amount: amount.toString(),
            ...r, total_ms: Date.now() - tStart });
        } catch (e: any) {
          const msg = e?.message?.slice(0, 200) ?? '';
          const detail = describeError(e);   // unwrapped cause, not the wrapper
          failed++;
          if (isDustBlocked(msg)) { dustBlocked++; await sleep(1000); } else await sleep(200);
          logRec({ phase, wallet: b.spec.label, error: detail.slice(0, 600), total_ms: Date.now() - tStart });
        }
      }
    };
    const ticker = setInterval(() => {
      process.stdout.write(`[${new Date().toISOString().slice(11, 19)}] ` +
        `submitted=${submitted} failed=${failed} dust-blocked=${dustBlocked}\r`);
    }, 3000);
    const watchdogs = reviveEnabled ? bundles.map((b) => startWatchdog(b, deadline)) : [];
    await Promise.all(bundles.map((b, i) => worker(b, i)));
    await Promise.allSettled(watchdogs);
    clearInterval(ticker);
  }

  const t1 = new Date().toISOString();
  console.log(`\n\n${phase} done. ${submitted} submitted, ${failed} failed, ` +
    `${dustBlocked} dust-blocked, ${revivals} wallet revival(s), ` +
    `${bundles.reduce((a, b) => a + b.resplits, 0)} re-split(s), ` +
    `${retriedTotal} transient retry(ies), ${timedOut} stage timeout(s).`);
  if (timedOut > 0) {
    console.log(`\nNOTE: ${timedOut} call(s) hung and were released by timeout. Each cost that`);
    console.log('lane one cycle but did NOT retire it -- pre-timeout, a single hang removed a');
    console.log('lane for the rest of the run. Persistent timeouts point at the proof server');
    console.log('or node, not at this harness.');
  }
  if (revivals > 0) {
    console.log(`\nNOTE: ${revivals} wallet(s) had to be rebuilt mid-run. Each revival costs a`);
    console.log('full cold sync, during which that lane produced nothing -- so throughput');
    console.log('figures are an UNDERSTATEMENT of capacity and an OVERSTATEMENT of stability.');
    console.log('Repeated revivals almost always mean the indexer is rate-limiting us.');
  }
  console.log(`window: ${t0} .. ${t1}`);
  if (dustBlocked > submitted / 4) {
    console.log(`\nNOTE: dust-blocked ${dustBlocked} times vs ${submitted} submitted -- this fleet is`);
    console.log('DUST-limited, not prover- or node-limited. Add engines (--engines) and re-split,');
    console.log('or let the existing engines accrue longer. Engine count == max in-flight txs.');
  }
  console.log('\nMeasure what this did to the chain:');
  console.log(`  python3 midnight_dust_probe.py --endpoint <indexer> \\`);
  console.log(`    --from-time ${t0} --to-time ${t1} --out-dir ${phase}_out`);
  await shutdown(started);
}

main().then(() => process.exit(0)).catch((e) => { console.error(e); process.exit(1); });
