/**
 * wallet_status.ts — report real balances, and register NIGHT UTXOs for DUST
 * generation ("delegate").
 *
 * Two jobs, deliberately in one place because the second needs the first:
 *
 *   npx tsx src/wallet_status.ts --seed <hex|mnemonic>          # report only
 *   npx tsx src/wallet_status.ts --wallets wallets.json         # whole fleet
 *   npx tsx src/wallet_status.ts --wallets wallets.json --delegate
 *
 * VERIFIED against installed SDK types:
 *   state.unshielded.balances         Record<RawTokenType, bigint>
 *   state.unshielded.availableCoins   readonly UtxoWithMeta[]
 *   state.unshielded.address          UnshieldedAddress
 *   state.dust.balance(date)          bigint  (SPECK)
 *   state.dust.address                DustAddress
 *   UtxoWithMeta = { utxo: {type,value,owner,intentHash,outputNo},
 *                    meta: {ctime, registeredForDustGeneration} }
 *   facade.registerNightUtxosForDustGeneration(
 *       nightUtxos, nightVerifyingKey, signDustRegistration, dustReceiverAddress?)
 *     -> UnprovenTransactionRecipe
 *   facade.finalizeRecipe(recipe) -> FinalizedTransaction
 *   facade.submitTransaction(tx)  -> TransactionIdentifier
 *   keystore.getPublicKey() -> SignatureVerifyingKey   (the nightVerifyingKey)
 *   keystore.signData(bytes) -> Signature              (the signing callback)
 *
 * IDEMPOTENCY: each UTXO carries meta.registeredForDustGeneration, so --delegate
 * only submits for UTXOs that are NOT yet registered. Re-running is safe and does
 * nothing once everything is registered. This also means new NIGHT arriving later
 * needs another --delegate run: registration is per UTXO, not per wallet.
 *
 * WHY DELEGATION IS REQUIRED: DUST is generated by registered NIGHT UTXOs.
 * Unregistered NIGHT generates nothing, so the wallet can hold plenty of NIGHT and
 * still be unable to pay a single fee.
 */

import { readFileSync } from 'node:fs';
import * as ledger from '@midnight-ntwrk/ledger-v8';
import { buildWallet, NETWORK_ID } from './providers.js';
import { deriveAddresses } from './derive_addresses.js';

const SPECKS_PER_DUST = 1_000_000_000_000_000n;
const STARS_PER_NIGHT = 1_000_000n;

function parseArgs() {
  const a: Record<string, string> = {};
  const flags = new Set<string>();
  const argv = process.argv.slice(2);
  for (let i = 0; i < argv.length; i++) {
    if (!argv[i].startsWith('--')) continue;
    const k = argv[i].slice(2);
    if (argv[i + 1] === undefined || argv[i + 1].startsWith('--')) flags.add(k);
    else a[k] = argv[++i];
  }
  return { a, flags };
}

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

// ONLY NIGHT UTXOs can generate DUST. The native NIGHT token type is all-zeros
// (or empty); anything else -- change from contract calls, faucet drips of other
// assets -- is a non-Night asset that registerNightUtxosForDustGeneration
// REJECTS with "Token of a non-Night type received".
//
// This must be applied to the UNREGISTERED COUNT too, not just to the delegate
// filter. Counting non-NIGHT UTXOs as "needing delegation" made the fleet
// summary demand a --delegate run forever, while --delegate itself correctly
// skipped them and reported "nothing to do" -- so the tool contradicted itself
// and looked like delegation was silently failing.
export function isNightTokenType(t: unknown): boolean {
  const s = String(t ?? '');
  return s === '' || /^0+$/.test(s);
}

/** Format a raw bigint with a divisor, without floating point. */
function fmtUnits(raw: bigint, per: bigint, dp: number): string {
  const whole = raw / per;
  const frac = raw % per;
  const fracStr = frac.toString().padStart(per.toString().length - 1, '0').slice(0, dp);
  return `${whole}.${fracStr}`;
}

interface Report {
  dustCoins?: { available: number; pending: number; total: number };
  availableDustSpeck?: bigint;
  dustCoinDetail?: string[];
  label: string;
  unshieldedAddress: string;
  dustAddress: string;
  synced: boolean;
  nightBalances: { tokenType: string; raw: bigint; night: string }[];
  dustSpeck: bigint;
  utxos: {
    type: string; value: bigint; intentHash: string; outputNo: number;
    registered: boolean; ctime: string;
  }[];
  /** Unregistered NIGHT UTXOs -- the only ones --delegate can act on. */
  unregisteredCount: number;
  /** Unregistered non-NIGHT UTXOs -- can NEVER be registered; informational. */
  unregisteredNonNight: number;
}

// Delegation-specific sync gate. The generic waitForSync accepts lag===0 even at
// 0/0 (the false-complete), which for --delegate is dangerous: a fresh wallet
// whose NIGHT UTXO has not loaded yet reads unregisteredCount=0 and gets SILENTLY
// SKIPPED -- you would think the whole fleet delegated when some did not. So
// before delegating we require the UNSHIELDED wallet to have actually advanced
// (appliedIndex>0, connected, caught up) AND to show at least one coin. We do NOT
// gate on dust here: dust is zero by definition until delegation succeeds.
async function waitForUnshieldedFunds(
  wallet: any, timeoutMs: number, label: string,
): Promise<boolean> {
  return new Promise<boolean>((resolve) => {
    let done = false;
    const finish = (v: boolean) => {
      if (done) return; done = true;
      try { sub.unsubscribe?.(); } catch { /* ignore */ }
      clearTimeout(timer); resolve(v);
    };
    const timer = setTimeout(() => finish(false), timeoutMs);
    const sub = wallet.state().subscribe((st: any) => {
      const pr = st?.unshielded?.progress;
      if (!pr) return;
      const applied = BigInt(pr.appliedIndex ?? 0);
      const relevant = BigInt(pr.highestRelevantWalletIndex ?? 0);
      const lag = relevant > applied ? relevant - applied : applied - relevant;
      const connected = Boolean(pr.isConnected);
      const coins = (st?.unshielded?.availableCoins ?? []).length;
      // Real: advanced past genesis, caught up, connected, and a NIGHT coin present.
      if (applied > 0n && connected && lag === 0n && coins > 0) finish(true);
    });
  });
}

async function waitForSync(wallet: any, timeoutMs: number, quiet = false): Promise<any> {
  let last = '';
  const sub = wallet.state().subscribe((st: any) => {
    if (quiet) return;
    const pr = st?.unshielded?.progress;
    if (!pr) return;
    // Show the field that ACTUALLY decides syncedness. The SDK computes
    //   isStrictlyComplete() = isConnected && |highestRelevantWalletIndex - appliedIndex| === 0
    // so highestRelevantWalletIndex is the denominator that matters.
    // highestIndex is the chain-wide figure and is irrelevant to being synced --
    // displaying it as the denominator made a synced-and-empty wallet look stuck.
    const applied = BigInt(pr.appliedIndex ?? 0);
    const relevant = BigInt(pr.highestRelevantWalletIndex ?? 0);
    const chainHigh = BigInt(pr.highestIndex ?? 0);
    const lag = relevant > applied ? relevant - applied : applied - relevant;
    const complete = Boolean(pr.isConnected) && lag === 0n;
    const line =
      `    applied=${applied} relevantForWallet=${relevant} lag=${lag}` +
      `  chainHighest=${chainHigh}  connected=${pr.isConnected}` +
      `  ${complete ? 'SYNCED' : 'syncing'}` +
      (complete && relevant === 0n
        ? '  <- synced with ZERO history: indexer sees no txs for this address'
        : '');
    if (line !== last) { last = line; console.log(line); }
  });
  const res = await Promise.race([
    wallet.waitForSyncedState().then((st: any) => ({ ok: true as const, st })),
    sleep(timeoutMs).then(() => ({ ok: false as const, st: undefined })),
  ]);
  try { sub.unsubscribe?.(); } catch { /* ignore */ }
  if (!res.ok) {
    const latest = await new Promise<any>((resolve) => {
      const s2 = wallet.state().subscribe((st: any) => { resolve(st); try { s2.unsubscribe?.(); } catch {} });
      setTimeout(() => resolve(undefined), 5000);
    });
    return { ok: false, st: latest };
  }
  return res;
}

function buildReport(label: string, addrs: any, st: any, synced: boolean): Report {
  const balances: Record<string, bigint> = st?.unshielded?.balances ?? {};
  const nightBalances = Object.entries(balances).map(([tokenType, raw]) => ({
    tokenType,
    raw: raw as bigint,
    night: fmtUnits(raw as bigint, STARS_PER_NIGHT, 6),
  }));

  let dustSpeck = 0n;
  try {
    dustSpeck = st?.dust?.balance ? st.dust.balance(new Date()) : 0n;
  } catch { /* balance() can throw pre-sync */ }

  // The balancer spends AVAILABLE coins, not the headline balance. A large
  // balance() with zero availableCoins is exactly the "could not balance dust"
  // failure -- the dust exists but isn't in spendable coin form yet.
  const dustCoins = {
    available: (st?.dust?.availableCoins ?? []).length,
    pending: (st?.dust?.pendingCoins ?? []).length,
    total: (st?.dust?.totalCoins ?? []).length,
  };
  // DustFullInfo values live in generatedNow (current spendable Specks for that
  // coin), NOT a `value` field. maxCap is the eventual ceiling; rate is the slope.
  // The balancer spends generatedNow at balancing time, so THIS is the number that
  // must exceed the deploy fee.
  let availableDustSpeck = 0n;
  let dustCoinDetail: string[] = [];
  try {
    for (const c of st?.dust?.availableCoins ?? []) {
      const gen = BigInt(c?.generatedNow ?? 0);
      const cap = BigInt(c?.maxCap ?? 0);
      availableDustSpeck += gen;
      const ctime = c?.token?.ctime ? new Date(c.token.ctime).toISOString() : '?';
      dustCoinDetail.push(
        `generatedNow=${fmtUnits(gen, SPECKS_PER_DUST, 6)} maxCap=${fmtUnits(cap, SPECKS_PER_DUST, 6)} ctime=${ctime}`,
      );
    }
  } catch { /* shape varies */ }

  const coins: readonly any[] = st?.unshielded?.availableCoins ?? [];
  const utxos = coins.map((c) => ({
    type: String(c.utxo?.type ?? ''),
    value: (c.utxo?.value ?? 0n) as bigint,
    intentHash: String(c.utxo?.intentHash ?? ''),
    outputNo: Number(c.utxo?.outputNo ?? 0),
    registered: Boolean(c.meta?.registeredForDustGeneration),
    ctime: c.meta?.ctime ? new Date(c.meta.ctime).toISOString() : '',
  }));

  return {
    dustCoins,
    availableDustSpeck,
    dustCoinDetail,
    label,
    unshieldedAddress: addrs.unshieldedAddress,
    dustAddress: addrs.dustAddress ?? '',
    synced,
    nightBalances,
    dustSpeck,
    utxos,
    unregisteredCount: utxos.filter((u) => !u.registered && isNightTokenType(u.type)).length,
    unregisteredNonNight: utxos.filter((u) => !u.registered && !isNightTokenType(u.type)).length,
  };
}

function printReport(r: Report) {
  console.log(`\n=== ${r.label} ${r.synced ? '' : '(NOT fully synced -- figures may lag)'}`);
  console.log(`  unshielded: ${r.unshieldedAddress}`);
  console.log(`  dust addr:  ${r.dustAddress}`);

  if (r.nightBalances.length === 0) {
    console.log('  NIGHT: none seen.');
    console.log('    Confirm with the indexer directly (bypasses the SDK):');
    console.log(`      npx tsx src/test_address.ts --address ${r.unshieldedAddress}`);
    console.log('    If that reports highestTransactionId=0, the indexer has no txs for');
    console.log('    this address and the funding went somewhere else.');
  } else {
    for (const b of r.nightBalances) {
      console.log(`  NIGHT: ${b.night}  (${b.raw} STAR, token ${b.tokenType.slice(0, 20)}...)`);
    }
  }
  console.log(`  DUST:  ${fmtUnits(r.dustSpeck, SPECKS_PER_DUST, 15)}  (${r.dustSpeck} SPECK, headline balance)`);
  if (r.dustCoins) {
    console.log(`  DUST coins: ${r.dustCoins.available} available, ${r.dustCoins.pending} pending, ${r.dustCoins.total} total`);
    console.log(`  DUST generatedNow (spendable by balancer): ${fmtUnits(r.availableDustSpeck ?? 0n, SPECKS_PER_DUST, 6)}`);
    for (const d of r.dustCoinDetail ?? []) console.log(`    coin: ${d}`);
    console.log('  The balancer pays fees from a SINGLE coin\'s generatedNow (it picks the');
    console.log('  smallest coin that covers the fee). With one coin, that coin\'s generatedNow');
    console.log('  must exceed the whole deploy fee. If generatedNow is small vs a k=18 proof');
    console.log('  fee, that is the "could not balance dust" cause -- let it generate more, or');
    console.log('  fund a second registered NIGHT UTXO so there are multiple coins to draw on.');
  }

  if (r.utxos.length === 0) {
    console.log('  UTXOs: none');
  } else {
    console.log(`  UTXOs (${r.utxos.length}, ${r.unregisteredCount} NIGHT NOT registered for DUST` +
      (r.unregisteredNonNight ? `, ${r.unregisteredNonNight} non-NIGHT (never registerable)` : '') + '):');
    for (const u of r.utxos) {
      // Label the token honestly. Printing "NIGHT" against every UTXO hid the
      // fact that the unregistered ones here were a DIFFERENT token, which is
      // exactly why they could never be delegated.
      const night = isNightTokenType(u.type);
      const unit = night ? 'NIGHT' : `tok:${u.type.slice(0, 10)}..`;
      console.log(
        `    ${u.registered ? 'registered  ' : 'UNREGISTERED'} ` +
        `${fmtUnits(u.value, STARS_PER_NIGHT, 6).padStart(14)} ${unit}  ` +
        `${u.intentHash.slice(0, 16)}...#${u.outputNo}  ${u.ctime}`,
      );
    }
    if (r.unregisteredNonNight > 0 && r.unregisteredCount === 0) {
      console.log('  -> the UNREGISTERED UTXOs above are NOT NIGHT, so they cannot generate');
      console.log('     DUST and --delegate will correctly skip them. Nothing to do here.');
    }
  }
  // A zero DUST reading is only meaningful on a SYNCED dust sub-wallet. Mid-sync
  // it is just "not loaded yet", and reporting it bare is what made a wallet at
  // max cap look like a failed delegation.
  const dustUnknown = !r.synced && (r.dustCoins?.total ?? 0) === 0;
  if (dustUnknown) {
    console.log('  -> DUST figures are NOT TRUSTWORTHY: the dust sub-wallet had not');
    console.log('     finished syncing when this was read, so 0 means "unknown", not');
    console.log('     "none". Re-run with a longer --sync-timeout-ms, or watch it live:');
    console.log(`       npx tsx src/diag_dust.ts --wallets <file> --only ${r.label}`);
  } else if (r.dustSpeck === 0n && r.unregisteredCount > 0) {
    console.log('  -> DUST is zero and NIGHT is unregistered. Run with --delegate.');
  } else if (r.dustSpeck === 0n && r.utxos.length > 0) {
    console.log('  -> NIGHT is registered but DUST is still 0. Generation takes time');
    console.log('     (roughly a week to reach the cap); re-check shortly.');
  }
}

/** Register every not-yet-registered NIGHT UTXO for DUST generation. */
async function delegate(bundle: any, r: Report): Promise<void> {
  const st = await new Promise<any>((resolve) => {
    const s = bundle.wallet.state().subscribe((x: any) => { resolve(x); try { s.unsubscribe?.(); } catch {} });
  });
  const coins: readonly any[] = st?.unshielded?.availableCoins ?? [];

  // ONLY NIGHT UTXOs can generate DUST. The NIGHT token type is all-zeros; any
  // other token (e.g. change/outputs from earlier contract-call tests) is a
  // non-Night asset that registerNightUtxosForDustGeneration REJECTS with
  // "Token of a non-Night type received". Filter to NIGHT before registering.
  const isNight = (c: any) => isNightTokenType(c.utxo?.type);
  const nonNight = coins.filter((c) => !c.meta?.registeredForDustGeneration && !isNight(c));
  const pending = coins.filter((c) => !c.meta?.registeredForDustGeneration && isNight(c));

  if (nonNight.length > 0) {
    console.log(`  delegate: skipping ${nonNight.length} non-NIGHT UTXO(s) -- only NIGHT`);
    console.log(`    generates DUST. Token types: ` +
      nonNight.map((c: any) => String(c.utxo?.type ?? '').slice(0, 12) + '...').join(', '));
  }
  if (pending.length === 0) {
    console.log('  delegate: nothing to do -- no unregistered NIGHT UTXOs.');
    return;
  }
  console.log(`  delegate: registering ${pending.length} UTXO(s) for DUST generation...`);

  // Fee preview before committing.
  try {
    const est = await bundle.wallet.estimateRegistration(pending);
    console.log(`    estimated fee: ${fmtUnits(est.fee, SPECKS_PER_DUST, 15)} DUST (${est.fee} SPECK)`);
    if (est.fee > 0n && r.dustSpeck === 0n) {
      console.log('    NOTE: the registration transaction itself costs DUST, and this wallet');
      console.log('    has none yet. If submission fails for insufficient DUST, that is why --');
      console.log('    the network must have a path for the first registration (or fund DUST');
      console.log('    another way). Attempting anyway so the error is explicit.');
    }
  } catch (e: any) {
    console.log(`    (fee estimate unavailable: ${e.message?.slice(0, 100)})`);
  }

  const nightVerifyingKey = bundle.unshieldedKeystore.getPublicKey();
  const signDustRegistration = (payload: Uint8Array) =>
    bundle.unshieldedKeystore.signData(payload);

  // Send generated DUST to this wallet's own dust address.
  const dustReceiver = st?.dust?.address;

  // Each of these three stages was previously silent. The finalize step in
  // particular invokes the PROOF SERVER, and a first proof downloads ~GB of
  // prover-key params before it can even begin -- which looks exactly like a
  // hang. Stage logs + elapsed timing distinguish "proving" from "wedged".
  const stage = (label: string, t0: number) =>
    console.log(`    [${((Date.now() - t0) / 1000).toFixed(1)}s] ${label}`);

  const tRecipe = Date.now();
  console.log('    building registration recipe...');
  const recipe = await bundle.wallet.registerNightUtxosForDustGeneration(
    pending,
    nightVerifyingKey,
    signDustRegistration,
    dustReceiver,
  );
  stage('recipe built; finalizing (this calls the PROOF SERVER -- first proof', tRecipe);
  console.log('    downloads ~GB of prover params, so a long pause here is NORMAL,');
  console.log('    not a hang; watch the proof-server container logs for activity)...');

  const tFinal = Date.now();
  const finalized = await bundle.wallet.finalizeRecipe(recipe);
  stage('finalized (proof generated); submitting to node...', tFinal);

  const tSubmit = Date.now();
  const txId = await bundle.wallet.submitTransaction(finalized);
  stage(`submitted registration tx: ${txId}`, tSubmit);
  console.log('    DUST generation begins once this confirms. Re-run without --delegate');
  console.log('    to confirm the UTXOs flip to "registered".');
}

async function main() {
  const { a, flags } = parseArgs();
  const doDelegate = flags.has('delegate');
  // 600s, deliberately matching providers.waitForRealSync's default. The old 180s
  // was SHORTER than a cold DUST sync on preview (~5-6 min to replay to the
  // current relevant index, and growing with chain history), so the race below
  // expired mid-sync and printReport published the partial state -- 0 coins, 0
  // balance -- as though it were a fact. That reads exactly like "delegation did
  // not work" on a wallet that actually holds DUST at max cap. The load
  // generators never hit this because they wait 600s; only this tool gave up
  // early, so status and load_test disagreed about the same wallet.
  const timeoutMs = Number(a['sync-timeout-ms'] ?? process.env.MN_SYNC_TIMEOUT_MS ?? 600_000);

  let wallets: { label: string; seed: string }[];
  if (a.seed) {
    wallets = [{ label: a.label ?? 'wallet', seed: a.seed }];
  } else if (a.wallets) {
    wallets = JSON.parse(readFileSync(a.wallets, 'utf8'));
  } else {
    const s = process.env.MIDNIGHT_PREPROD_SEED ?? process.env.MIDNIGHT_PREPROD_MNEMONIC;
    if (!s) throw new Error('pass --seed, --wallets, or set MIDNIGHT_PREPROD_SEED');
    wallets = [{ label: 'env', seed: s }];
  }
  if (a.only) wallets = wallets.filter((w) => w.label === a.only);
  if (!wallets.length) throw new Error('no wallets selected');

  console.log(`network: ${NETWORK_ID}   wallets: ${wallets.length}` +
    `   mode: ${doDelegate ? 'REPORT + DELEGATE' : 'report only'}`);

  const reports: Report[] = [];
  for (const w of wallets) {
    const addrs = deriveAddresses(w.label, w.seed);
    console.log(`\n--- ${w.label} ---`);
    let bundle: any;
    try {
      bundle = await buildWallet(w.seed);
    } catch (e: any) {
      console.error(`  buildWallet failed: ${e.message?.slice(0, 160)}`);
      continue;
    }
    const { ok, st } = await waitForSync(bundle.wallet, timeoutMs, wallets.length > 3);
    const r = buildReport(w.label, addrs, st, ok);
    reports.push(r);
    printReport(r);

    if (doDelegate && r.unregisteredCount > 0) {
      try {
        await delegate(bundle, r);
      } catch (e: any) {
        console.error(`  delegate FAILED: ${e.message?.slice(0, 300)}`);
      }
    } else if (doDelegate) {
      // r.unregisteredCount === 0 here. That is either (a) genuinely all
      // registered, or (b) the NIGHT UTXO had not synced when we read it -- the
      // 0/0 false-complete -- in which case skipping would silently drop this
      // wallet from the fleet. Distinguish the two before trusting the skip.
      const hasFunds = r.nightBalances.some((b) => b.raw > 0n);
      if (!hasFunds) {
        console.log('  waiting for NIGHT UTXO to sync before trusting the skip...');
        const arrived = await waitForUnshieldedFunds(bundle.wallet, timeoutMs, w.label);
        if (arrived) {
          const st2 = (await waitForSync(bundle.wallet, timeoutMs, true)).st;
          const r2 = buildReport(w.label, addrs, st2, true);
          if (r2.unregisteredCount > 0) {
            console.log('  NIGHT UTXO appeared after a slow sync; delegating now.');
            try { await delegate(bundle, r2); }
            catch (e: any) { console.error(`  delegate FAILED: ${e.message?.slice(0, 300)}`); }
          } else if (r2.nightBalances.some((b) => b.raw > 0n)) {
            console.log('  delegate: skipped (every NIGHT UTXO is already registered).');
          } else {
            console.log('  delegate: SKIPPED but this wallet has NO NIGHT -- fund it first.');
          }
        } else {
          console.error('  delegate: NIGHT UTXO did not sync in time -- NOT delegated. ' +
            'This wallet needs funding or a longer MN_SYNC_TIMEOUT_MS; re-run --delegate.');
        }
      } else {
        console.log('  delegate: skipped (every NIGHT UTXO is already registered).');
      }
    }

    try { await bundle.wallet.stop?.(); } catch { /* ignore */ }
  }

  // Fleet rollup.
  console.log(`\n===== fleet summary (${reports.length} wallets) =====`);
  const funded = reports.filter((r) => r.nightBalances.some((b) => b.raw > 0n));
  const withDust = reports.filter((r) => r.dustSpeck > 0n);
  // A wallet whose dust sub-wallet never finished syncing has UNKNOWN dust, not
  // zero. Folding those into "with DUST > 0: 0/N" is what made a fully funded
  // fleet look unfunded, so they get their own line.
  const dustUnknown = reports.filter(
    (r) => r.dustSpeck === 0n && !r.synced && (r.dustCoins?.total ?? 0) === 0,
  );
  const needDelegation = reports.filter((r) => r.unregisteredCount > 0);
  console.log(`  with NIGHT:              ${funded.length}/${reports.length}`);
  console.log(`  with DUST > 0:           ${withDust.length}/${reports.length}`);
  if (dustUnknown.length) {
    console.log(`  DUST UNKNOWN (unsynced): ${dustUnknown.length}  ` +
      `<- not zero; re-read with a longer --sync-timeout-ms`);
    console.log(`    ${dustUnknown.map((r) => r.label).join(', ')}`);
  }
  console.log(`  needing delegation:      ${needDelegation.length}  (NIGHT UTXOs only)`);
  if (needDelegation.length) {
    console.log(`    ${needDelegation.map((r) => r.label).join(', ')}`);
    if (!doDelegate) console.log('    re-run with --delegate to register them');
  }
  console.log('\nA wallet can only transact when DUST > 0. NIGHT alone is not enough.');
}

main().catch((e) => { console.error(e); process.exit(1); });